name: ğŸš€ğŸš€ Basic ğŸ‘¨â€ğŸ’»Dev - SecğŸª² OpğŸ“‰ ğŸš€ğŸš€  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build Workflow
      run: echo "ğŸ—ï¸ Dummy Step, compile, package, create container for application and ..."

  test:
    runs-on: ubuntu-latest
    steps:
    - name: sast
      run: echo "ğŸ—ï¸ test, job sast step"

  depploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy application in azure container
      run: echo "ğŸ—ï¸ Deploying ..."

  dast:
    runs-on: ubuntu-latest

    steps:
    - name: DAST analysis
      run: |
        echo "ğŸ—ï¸ Runing DAST Analysis"
